# Generated by Django 5.2.1 on 2026-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_sync_specialoffer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='banner',
            field=models.ImageField(upload_to='special_offer_banners/'),
        ),
    ]
